### ISSUE TITLE
Error: YAMLException: bad indentation of a mapping entry from reading heuristic.yml on Windows machine

### ISSUE THREAD

**Issue by xfkoko** [Nixinova/LinguistJS#37]
Hello!

I'm trying to run the tool locally on a Windows machine and get this error:
```
Error: YAMLException: bad indentation of a mapping entry (752:7)

 749 |   - language: Hosts File
 750 |     pattern: '(?xi) ^(?<ipv4>(?!\.)(? ...
 751 |
 752 |       (?=$|\s)
-------------^
 753 |   - language: Adblock Filter List
 754 |     pattern: '\A\[(?<version>(?:[Aa]d ...
    at generateError (C:\etl-pipelines\node_modules\js-yaml\lib\loader.js:183:10)
    at throwError (C:\etl-pipelines\node_modules\js-yaml\lib\loader.js:187:9)
    at readBlockMapping (C:\etl-pipelines\node_modules\js-yaml\lib\loader.js:1182:7)
    at composeNode (C:\etl-pipelines\node_modules\js-yaml\lib\loader.js:1441:12)
    at readBlockSequence (C:\etl-pipelines\node_modules\js-yaml\lib\loader.js:1008:5)
    at composeNode (C:\etl-pipelines\node_modules\js-yaml\lib\loader.js:1472:45)
    at readBlockMapping (C:\etl-pipelines\node_modules\js-yaml\lib\loader.js:1164:11)
    at composeNode (C:\etl-pipelines\node_modules\js-yaml\lib\loader.js:1441:12)
    at readBlockSequence (C:\etl-pipelines\node_modules\js-yaml\lib\loader.js:1008:5)
    at composeNode (C:\etl-pipelines\node_modules\js-yaml\lib\loader.js:1472:45) {
  reason: 'bad indentation of a mapping entry',
```
Tracked it to this file that the tool is trying to read:
https://github.com/github-linguist/linguist/blob/f164d13fa618023ecf2d8f2ed9a6ce5fae731346/lib/linguist/heuristics.yml#L818

Thinking it is starting from here in linguist-js:
https://github.com/Nixinova/LinguistJS/blob/f842e14ab7629791db76784dc9c1947df74d1da2/build/download-files.ts#L26

Tried different node versions, shells and WSL. Reproduces with my college with Windows machine but does not reproduce with my college with Mac. -> Narrowing the problem to be in the operating system?
Also, tried to run with offline true but it did not help.

Full Error:
```
Error: YAMLException: bad indentation of a mapping entry (752:7)

 749 |   - language: Hosts File
 750 |     pattern: '(?xi) ^(?<ipv4>(?!\.)(? ...
 751 |
 752 |       (?=$|\s)
-------------^
 753 |   - language: Adblock Filter List
 754 |     pattern: '\A\[(?<version>(?:[Aa]d ...
    at generateError (C:\etl-pipelines\node_modules\js-yaml\lib\loader.js:183:10)
    at throwError (C:\etl-pipelines\node_modules\js-yaml\lib\loader.js:187:9)
    at readBlockMapping (C:\etl-pipelines\node_modules\js-yaml\lib\loader.js:1182:7)
    at composeNode (C:\etl-pipelines\node_modules\js-yaml\lib\loader.js:1441:12)
    at readBlockSequence (C:\etl-pipelines\node_modules\js-yaml\lib\loader.js:1008:5)
    at composeNode (C:\etl-pipelines\node_modules\js-yaml\lib\loader.js:1472:45)
    at readBlockMapping (C:\etl-pipelines\node_modules\js-yaml\lib\loader.js:1164:11)
    at composeNode (C:\etl-pipelines\node_modules\js-yaml\lib\loader.js:1441:12)
    at readBlockSequence (C:\etl-pipelines\node_modules\js-yaml\lib\loader.js:1008:5)
    at composeNode (C:\etl-pipelines\node_modules\js-yaml\lib\loader.js:1472:45) {
  reason: 'bad indentation of a mapping entry',
  mark: {
    name: null,
    buffer: '\n' +
      '---\n' +
      'disambiguations:\n' +
      "- extensions: ['.1', '.2', '.3', '.4', '.5', '.6', '.7', '.8', '.9']\n" +
      '  rules:\n' +
      '  - language: Roff Manpage\n' +
      '    and:\n' +
      '    - named_pattern: mdoc-date\n' +
      '    - named_pattern: mdoc-title\n' +
      '    - named_pattern: mdoc-heading\n' +
      '  - language: Roff Manpage\n' +
      '    and:\n' +
      '    - named_pattern: man-title\n' +
      '    - named_pattern: man-heading\n' +
      '  - language: Roff\n' +
      `    pattern: '^\\.(?:[A-Za-z]{2}(?:\\s|$)|\\\\")'\n` +
      "- extensions: ['.1in', '.1m', '.1x', '.3in', '.3m', '.3p', '.3pm', '.3qt', '.3x', '.man', '.mdoc']\n" +
      '  rules:\n' +
      '  - language: Roff Manpage\n' +
      '    and:\n' +
      '    - named_pattern: mdoc-date\n' +
      '    - named_pattern: mdoc-title\n' +
      '    - named_pattern: mdoc-heading\n' +
      '  - language: Roff Manpage\n' +
      '    and:\n' +
      '    - named_pattern: man-title\n' +
      '    - named_pattern: man-heading\n' +
      '  - language: Roff\n' +
      "- extensions: ['.al']\n" +
      '  rules:\n' +
      '  - language: AL\n' +
      '    and:\n' +
      "    - pattern: '\\b(?i:(CODEUNIT|PAGE|PAGEEXTENSION|PAGECUSTOMIZATION|DOTNET|ENUM|ENUMEXTENSION|VALUE|QUERY|REPORT|TABLE|TABLEEXTENSION|XMLPORT|PROFILE|CONTROLADDIN|REPORTEXTENSION|INTERFACE|PERMISSIONSET|PERMISSIONSETEXTENSION|ENTITLEMENT))\\b'\n" +
      '  - language: Perl\n' +
      "- extensions: ['.app']\n" +
      '  rules:\n' +
      '  - language: Erlang\n' +
      "    pattern: '^\\{\\s*(?:application|''application'')\\s*,\\s*(?:[a-z]+[\\w@]*|''[^'']+'')\\s*,\\s*\\[(?:.|[\\r\\n])*\\]\\s*\\}\\.[ \\t]*$'\n" +
      "- extensions: ['.as']\n" +
      '  rules:\n' +
      '  - language: ActionScript\n' +
      "    pattern: '^\\s*(?:package(?:\\s+[\\w.]+)?\\s+(?:\\{|$)|import\\s+[\\w.*]+\\s*;|(?=.*?(?:intrinsic|extends))(intrinsic\\s+)?class\\s+[\\w<>.]+(?:\\s+extends\\s+[\\w<>.]+)?|(?:(?:public|protected|private|static)\\s+)*(?:(?:var|const|local)\\s+\\w+\\s*:\\s*[\\w<>.]+(?:\\s*=.*)?\\s*;|function\\s+\\w+\\s*\\((?:\\s*\\w+\\s*:\\s*[\\w<>.]+\\s*(,\\s*\\w+\\s*:\\s*[\\w<>.]+\\s*)*)?\\)))'\n" +
      "- extensions: ['.asc']\n" +
      '  rules:\n' +
      '  - language: Public Key\n' +
      "    pattern: '^(----[- ]BEGIN|ssh-(rsa|dss)) '\n" +
      '  - language: AsciiDoc\n' +
      "    pattern: '^[=-]+\\s|\\{\\{[A-Za-z]'\n" +
      '  - language: AGS Script\n' +
      "    pattern: '^(\\/\\/.+|((import|export)\\s+)?(function|int|float|char)\\s+((room|repeatedly|on|game)_)?([A-Za-z]+[A-Za-z_0-9]+)\\s*[;\\(])'\n" +
      "- extensions: ['.asm']\n" +
      '  rules:\n' +
      '  - language: Motorola 68K Assembly\n' +
      '    named_pattern: m68k\n' +
      "- extensions: ['.asy']\n" +
      '  rules:\n' +
      '  - language: LTspice Symbol\n' +
      "    pattern: '^SymbolType[ \\t]'\n" +
      '  - language: Asymptote\n' +
      "- extensions: ['.bas']\n" +
      '  rules:\n' +
      '  - language: B4X\n' +
      "    pattern: '\\A\\W{0,3}(?:.*(?:\\r?\\n|\\r)){0,9}B4(?:J|A|R|i)=true'\n" +
      '  - language: FreeBasic\n' +
      "    pattern: '^[ \\t]*#(?i)(?:define|endif|endmacro|ifn?def|include|lang|macro)(?:$|\\s)'\n" +
      '  - language: BASIC\n' +
      "    pattern: '\\A\\s*\\d'\n" +
      '  - language: VBA\n' +
      '    and:\n' +
      '    - named_pattern: vb-module\n' +
      '    - named_pattern: vba\n' +
      '  - language: Visual Basic 6.0\n' +
      '    named_pattern: vb-module\n' +
      "- extensions: ['.bb']\n" +
      '  rules:\n' +
      '  - language: BlitzBasic\n' +
      "    pattern: '(<^\\s*; |End Function)'\n" +
      '  - language: BitBake\n' +
      "    pattern: '^(# |include|require|inherit)\\b'\n" +
      '  - language: Clojure\n' +
      "    pattern: '\\((def|defn|defmacro|let)\\s'\n" +
      "- extensions: ['.bf']\n" +
      '  rules:\n' +
      '  - language: Beef\n' +
      "    pattern: '(?-m)^\\s*using\\s+(System|Beefy)(\\.(.*))?;\\s*$'\n" +
      '  - language: HyPhy\n' +
      '    pattern:\n' +
      `    - '(?-m)^\\s*#include\\s+".*";\\s*$'\n` +
      "    - '\\sfprintf\\s*\\('\n" +
      '  - language: Brainfuck\n' +
      "    pattern: '(>\\+>|>\\+<)'\n" +
      "- extensions: ['.bi']\n" +
      '  rules:\n' +
      '  - language: FreeBasic\n' +
      "    pattern: '^[ \\t]*#(?i)(?:define|endif|endmacro|ifn?def|if|include|lang|macro)(?:$|\\s)'\n" +
      "- extensions: ['.bs']\n" +
      '  rules:\n' +
      '  - language: Bikeshed\n' +
      `    pattern: '^(?i:<pre\\s+class)\\s*=\\s*(''|\\"|\\b)metadata\\b\\1[^>\\r\\n]*>'\n` +
      '  - language: BrighterScript\n' +
      '    pattern:\n' +
      '    - (?i:^\\s*(?=^sub\\s)(?:sub\\s*\\w+\\(.*?\\))|(?::\\s*sub\\(.*?\\))$)\n' +
      '    - (?i:^\\s*(end\\ssub)$)\n' +
      '    - (?i:^\\s*(?=^function\\s)(?:function\\s*\\w+\\(.*?\\)\\s*as\\s*\\w*)|(?::\\s*function\\(.*?\\)\\s*as\\s*\\w*)$)\n' +
      '    - (?i:^\\s*(end\\sfunction)$)\n' +
      '  - language: Bluespec BH\n' +
      "    pattern: '^package\\s+[A-Za-z_][A-Za-z0-9_'']*(?:\\s*\\(|\\s+where)'\n" +
      "- extensions: ['.builds']\n" +
      '  rules:\n' +
      '  - language: XML\n' +
      "    pattern: '^(\\s*)(?i:<Project|<Import|<Property|<?xml|xmlns)'\n" +
      "- extensions: ['.cairo']\n" +
      '  rules:\n' +
      '    - language: Cairo Zero\n' +
      "      pattern: '(^(\\s*)%lang(\\s+)([A-Za-z0-9_]+))|(^(\\s*)%builtins(\\s+)([A-Za-z0-9_]+\\s*)*$)|(^(\\s*)from(\\s+)starkware\\.(cairo|starknet)\\.([A-Za-z0-9_.\\s]+?)import)|(,\\s*ap\\+\\+;$)|(;\\s*ap\\+\\+$)'\n" +
      '    - language: Cairo\n' +
      "- extensions: ['.ch']\n" +
      '  rules:\n' +
      '  - language: xBase\n' +
      "    pattern: '^\\s*#\\s*(?i:if|ifdef|ifndef|define|command|xcommand|translate|xtranslate|include|pragma|undef)\\b'\n" +
      "- extensions: ['.cl']\n" +
      '  rules:\n' +
      '  - language: Common Lisp\n' +
      "    pattern: '^\\s*\\((?i:defun|in-package|defpackage) '\n" +
      '  - language: Cool\n' +
      "    pattern: '^class'\n" +
      '  - language: OpenCL\n' +
      "    pattern: '\\/\\* |\\/\\/ |^\\}'\n" +
      "- extensions: ['.cls']\n" +
      '  rules:\n' +
      '  - language: Visual Basic 6.0\n' +
      '    and:\n' +
      '    - named_pattern: vb-class\n' +
      "    - pattern: '^\\s*BEGIN(?:\\r?\\n|\\r)\\s*MultiUse\\s*=.*(?:\\r?\\n|\\r)\\s*Persistable\\s*='\n" +
      '  - language: VBA\n' +
      '    named_pattern: vb-class\n' +
      '  - language: TeX\n' +
      "    pattern: '^\\s*\\\\(?:NeedsTeXFormat|ProvidesClass)\\{'\n" +
      '  - language: ObjectScript\n' +
      "    pattern: '^Class\\s'\n" +
      "- extensions: ['.cmp']\n" +
      '  rules:\n' +
      '  - language: Gerber Image\n' +
      "    pattern: '^[DGMT][0-9]{2}\\*(?:\\r?\\n|\\r)'\n" +
      "- extensions: ['.cs']\n" +
      '  rules:\n' +
      '  - language: Smalltalk\n' +
      "    pattern: '![\\w\\s]+methodsFor: '\n" +
      "  - language: 'C#'\n" +
      "    pattern: '^\\s*(using\\s+[A-Z][\\s\\w.]+;|namespace\\s*[\\w\\.]+\\s*(\\{|;)|\\/\\/)'\n" +
      "- extensions: ['.csc']\n" +
      '  rules:\n' +
      '  - language: GSC\n' +
      '    named_pattern: gsc\n' +
      "- extensions: ['.csl']\n" +
      '  rules:\n' +
      '  - language: XML\n' +
      "    pattern: '(?i:^\\s*(<\\?xml|xmlns))'\n" +
      '  - language: Kusto\n' +
      "    pattern: '(^\\|\\s*(where|extend|project|limit|summarize))|(^\\.\\w+)'\n" +
      "- extensions: ['.d']\n" +
      '  rules:\n' +
      '  - language: D\n' +
      "    pattern: '^module\\s+[\\w.]*\\s*;|import\\s+[\\w\\s,.:]*;|\\w+\\s+\\w+\\s*\\(.*\\)(?:\\(.*\\))?\\s*\\{[^}]*\\}|unittest\\s*(?:\\(.*\\))?\\s*\\{[^}]*\\}'\n" +
      '  - language: DTrace\n' +
      "    pattern: '^(\\w+:\\w*:\\w*:\\w*|BEGIN|END|provider\\s+|(tick|profile)-\\w+\\s+\\{[^}]*\\}|#pragma\\s+D\\s+(option|attributes|depends_on)\\s|#pragma\\s+ident\\s)'\n" +
      '  - language: Makefile\n' +
      "    pattern: '([\\/\\\\].*:\\s+.*\\s\\\\$|: \\\\$|^[ %]:|^[\\w\\s\\/\\\\.]+\\w+\\.\\w+\\s*:\\s+[\\w\\s\\/\\\\.]+\\w+\\.\\w+)'\n" +    
      "- extensions: ['.dsp']\n" +
      '  rules:\n' +
      '  - language: Microsoft Developer Studio Project\n' +
      "    pattern: '# Microsoft Developer Studio Generated Build File'\n" +
      '  - language: Faust\n' +
      `    pattern: '\\bprocess\\s*[(=]|\\b(library|import)\\s*\\(\\s*"|\\bdeclare\\s+(name|version|author|copyright|license)\\s+"'\n` +     
      "- extensions: ['.e']\n" +
      '  rules:\n' +
      '  - language: E\n' +
      '    pattern:\n' +
      "    - '^\\s*(def|var)\\s+(.+):='\n" +
      "    - '^\\s*(def|to)\\s+(\\w+)(\\(.+\\))?\\s+\\{'\n" +
      "    - '^\\s*(when)\\s+(\\(.+\\))\\s+->\\s+\\{'\n" +
      '  - language: Eiffel\n' +
      '    pattern:\n' +
      "    - '^\\s*\\w+\\s*(?:,\\s*\\w+)*[:]\\s*\\w+\\s'\n" +
      "    - '^\\s*\\w+\\s*(?:\\(\\s*\\w+[:][^)]+\\))?(?:[:]\\s*\\w+)?(?:--.+\\s+)*\\s+(?:do|local)\\s'\n" +
      "    - '^\\s*(?:across|deferred|elseif|ensure|feature|from|inherit|inspect|invariant|note|once|require|undefine|variant|when)\\s*$'\n" +
      '  - language: Euphoria\n' +
      '    named_pattern: euphoria\n' +
      "- extensions: ['.ecl']\n" +
      '  rules:\n' +
      '  - language: ECLiPSe\n' +
      "    pattern: '^[^#]+:-'\n" +
      '  - language: ECL\n' +
      "    pattern: ':='\n" +
      "- extensions: ['.es']\n" +
      '  rules:\n' +
      '  - language: Erlang\n' +
      "    pattern: '^\\s*(?:%%|main\\s*\\(.*?\\)\\s*->)'\n" +
      '  - language: JavaScript\n' +
      `    pattern: '\\/\\/|["'']use strict["'']|export\\s+default\\s|\\/\\*(?:.|[\\r\\n])*?\\*\\/'\n` +
      "- extensions: ['.ex']\n" +
      '  rules:\n' +
      '  - language: Elixir\n' +
      '    pattern:\n' +
      "    - '^\\s*@moduledoc\\s'\n" +
      "    - '^\\s*(?:cond|import|quote|unless)\\s'\n" +
      "    - '^\\s*def(?:exception|impl|macro|module|protocol)[(\\s]'\n" +
      '  - language: Euphoria\n' +
      '    named_pattern: euphoria\n' +
      "- extensions: ['.f']\n" +
      '  rules:\n' +
      '  - language: Forth\n' +
      "    pattern: '^: '\n" +
      '  - language: Filebench WML\n' +
      "    pattern: 'flowop'\n" +
      '  - language: Fortran\n' +
      '    named_pattern: fortran\n' +
      "- extensions: ['.for']\n" +
      '  rules:\n' +
      '  - language: Forth\n' +
      "    pattern: '^: '\n" +
      '  - language: Fortran\n' +
      '    named_pattern: fortran\n' +
      "- extensions: ['.fr']\n" +
      '  rules:\n' +
      '  - language: Forth\n' +
      "    pattern: '^(: |also |new-device|previous )'\n" +
      '  - language: Frege\n' +
      "    pattern: '^\\s*(import|module|package|data|type) '\n" +
      '  - language: Text\n' +
      "- extensions: ['.frm']\n" +
      '  rules:\n' +
      '  - language: VBA\n' +
      '    and:\n' +
      '    - named_pattern: vb-form\n' +
      "    - pattern: '^\\s*Begin\\s+\\{[0-9A-Z\\-]*\\}\\s?'\n" +
      '  - language: Visual Basic 6.0\n' +
      '    and:\n' +
      '    - named_pattern: vb-form\n' +
      "    - pattern: '^\\s*Begin\\s+VB\\.Form\\s+'\n" +
      "- extensions: ['.fs']\n" +
      '  rules:\n' +
      '  - language: Forth\n' +
      "    pattern: '^(: |new-device)'\n" +
      "  - language: 'F#'\n" +
      "    pattern: '^\\s*(#light|import|let|module|namespace|open|type)'\n" +
      '  - language: GLSL\n' +
      "    pattern: '^\\s*(#version|precision|uniform|varying|vec[234])'\n" +
      '  - language: Filterscript\n' +
      "    pattern: '#include|#pragma\\s+(rs|version)|__attribute__'\n" +
      "- extensions: ['.ftl']\n" +
      '  rules:\n' +
      '  - language: FreeMarker\n' +
      "    pattern: '^(?:<|[a-zA-Z-][a-zA-Z0-9_-]+[ \\t]+\\w)|\\$\\{\\w+[^\\r\\n]*?\\}|^[ \\t]*(?:<#--.*?-->|<#([a-z]+)(?=\\s|>)[^>]*>.*?</#\\1>|\\[#--.*?--\\]|\\[#([a-z]+)(?=\\s|\\])[^\\]]*\\].*?\\[#\\2\\])'\n" +
      '  - language: Fluent\n' +
      "    pattern: '^-?[a-zA-Z][a-zA-Z0-9_-]* *=|\\{\\$-?[a-zA-Z][-\\w]*(?:\\.[a-zA-Z][-\\w]*)?\\}'\n" +
      "- extensions: ['.g']\n" +
      '  rules:\n' +
      '  - language: GAP\n' +
      "    pattern: '\\s*(Declare|BindGlobal|KeyDependentOperation|Install(Method|GlobalFunction)|SetPackageInfo)'\n" +
      '  - language: G-code\n' +
      "    pattern: '^[MG][0-9]+(?:\\r?\\n|\\r)'\n" +
      "- extensions: ['.gd']\n" +
      '  rules:\n' +
      '  - language: GAP\n' +
      "    pattern: '\\s*(Declare|BindGlobal|KeyDependentOperation)'\n" +
      '  - language: GDScript\n' +
      "    pattern: '\\s*(extends|var|const|enum|func|class|signal|tool|yield|assert|onready)'\n" +
      "- extensions: ['.gml']\n" +
      '  rules:\n' +
      '  - language: XML\n' +
      "    pattern: '(?i:^\\s*(<\\?xml|xmlns))'\n" +
      '  - language: Graph Modeling Language\n' +
      "    pattern: '(?i:^\\s*(graph|node)\\s+\\[$)'\n" +
      '  - language: Gerber Image\n' +
      "    pattern: '^[DGMT][0-9]{2}\\*$'\n" +
      '  - language: Game Maker Language\n' +
      "- extensions: ['.gs']\n" +
      '  rules:\n' +
      '  - language: GLSL\n' +
      "    pattern: '^#version\\s+[0-9]+\\b'\n" +
      '  - language: Gosu\n' +
      "    pattern: '^uses (java|gw)\\.'\n" +
      '  - language: Genie\n' +
      "    pattern: '^\\[indent=[0-9]+\\]'\n" +
      "- extensions: ['.gsc']\n" +
      '  rules:\n' +
      '  - language: GSC\n' +
      '    named_pattern: gsc\n' +
      "- extensions: ['.gsh']\n" +
      '  rules:\n' +
      '  - language: GSC\n' +
      '    named_pattern: gsc\n' +
      "- extensions: ['.gts']\n" +
      '  rules:\n' +
      '  - language: Gerber Image\n' +
      "    pattern: '^G0.'\n" +
      '  - language: Glimmer TS\n' +
      "    negative_pattern: '^G0.'\n" +
      "- extensions: ['.h']\n" +
      '  rules:\n' +
      '  - language: Objective-C\n' +
      '    named_pattern: objectivec\n' +
      '  - language: C++\n' +
      '    named_pattern: cpp\n' +
      '  - language: C\n' +
      "- extensions: ['.hh']\n" +
      '  rules:\n' +
      '  - langu'... 18047 more characters,
    position: 23103,
    line: 751,
    column: 6,
    snippet: ' 749 |   - language: Hosts File\n' +
      " 750 |     pattern: '(?xi) ^(?<ipv4>(?!\\.)(? ...\n" +
      ' 751 | \n' +
      ' 752 |       (?=$|\\s)\n' +
      '-------------^\n' +
      ' 753 |   - language: Adblock Filter List\n' +
      " 754 |     pattern: '\\A\\[(?<version>(?:[Aa]d ..."
  }
}
```

**Comment by MidnightCrowing** [comment]
Hello!
I also encountered this issue and made a small modification. After testing, it seems to resolve the problem.

**Comment by xfkoko** [comment]
Glad to hear I was not the only one with this issue 😄 
Thanks for the change!

**Comment by Nixinova** [comment]
Thanks for the detailed dive and fix!
